### ISSUE TITLE
manifest.json should request permissions to *.netflix.com, not just movies.netflix.com

### ISSUE THREAD

**Issue by NiyaNagi** [UltraNurd/netflix-rater#1]
Hi UltraNurd,

Thanks for putting this together.  When testing on my wife's 880 ratings, I noticed that the manifest only requests permissions to movies.netflix.com.  This leads to the extension being unable to rate movies that appear under dvd.netflix.com (which, in my wife's case, was around 3/4ths of them).  Snippet below should be changed from this:

``` javascript
{
    "manifest_version": 2,

    "name": "Netflix Rater",
    "description": "Bulk sets some Netflix ratings from a JSON input",
    "version": "1.0",

    "browser_action": {
        "default_title": "Rate!"
    },

    "permissions": [
        "http://movies.netflix.com/"
    ],

    "background": {
        "scripts": ["background.js"]
    }
}
```

to this:

``` javascript
{
    "manifest_version": 2,

    "name": "Netflix Rater",
    "description": "Bulk sets some Netflix ratings from a JSON input",
    "version": "1.0",

    "browser_action": {
        "default_title": "Rate!"
    },

    "permissions": [
        "http://*.netflix.com/"
    ],

    "background": {
        "scripts": ["background.js"]
    }
}
```

**Comment by UltraNurd** [comment]
Thanks Adam.

I've committed this fix. I'm surprised I didn't run into this in my test - for some reason my export only contained movies.netflix.com URLs, even though much of my viewing was DVDs. I wonder if it has something to do with which types of accounts you had when?
